<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>不規則陣列</RootNamespace>
    <AssemblyName>不規則陣列</AssemblyName>
    <AssemblyTitle>不規則陣列</AssemblyTitle>
    <Product>不規則陣列</Product>
    <Copyright>Copyright ©  2023</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
</Project>
