<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>linklist_Palindrome_cycle</RootNamespace>
    <AssemblyName>linklist_Palindrome_cycle</AssemblyName>
    <AssemblyTitle>linklist_Palindrome_cycle</AssemblyTitle>
    <Product>linklist_Palindrome_cycle</Product>
    <Copyright>Copyright ©  2022</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
</Project>
