<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>C__OOP_多型</RootNamespace>
    <AssemblyName>C# OOP 多型</AssemblyName>
    <AssemblyTitle>C# OOP 多型</AssemblyTitle>
    <Product>C# OOP 多型</Product>
    <Copyright>Copyright ©  2023</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
</Project>
