<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OOP_class_1</RootNamespace>
    <AssemblyName>OOP-class-1</AssemblyName>
    <AssemblyTitle>OOP-class-1</AssemblyTitle>
    <Product>OOP-class-1</Product>
    <Copyright>Copyright ©  2023</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
</Project>
